version: "3"

services:
  db:
    image: mysql:5.6
    ports:
      - 3315:3306
    volumes:
     - ./containers/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cms"

  xmr:
    image: xibosignage/xibo-xmr:release-0.7
    ports:
     - "9505:9505"
    environment:
      XMR_DEBUG: "true"
      IPV6RESPSUPPORT: "false"
      IPV6PUBSUPPORT: "false"

  web:
    build:
      context: .
      dockerfile: .docker/dev.Dockerfile
    env_file:
     - .docker/dev.config.env
    volumes:
     - ./:/var/www/cms
    ports:
     - "80:80"

  swagger:
      image: swaggerapi/swagger-ui:latest
      ports:
       - "8080:8080"
      environment:
        - API_URL=http://localhost/swagger.json